## Pre Processing

In [28]:
# Data Preprocessing Template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Importing the dataset
datatrain = pd.read_csv('C:/Users/chall/Desktop/edu/ml/themljourneybegins/kaggle/titanic/train.csv')
datatest = pd.read_csv('C:/Users/chall/Desktop/edu/ml/themljourneybegins/kaggle/titanic/test.csv')
y_train = datatrain.iloc[:,[1]].values
y = np.ravel(y_train)

X = datatrain.iloc[:,[2,4,5,6,7,9]].values
X_test_out = datatest.iloc[:,[1,3,4,5,6,8]].values

#dealing with null values
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values= 'NaN', strategy="mean",axis= 0)
X[:,[2]] = imp.fit_transform(X[:,[2]])
X_test_out[:,[2]] = imp.fit_transform(X_test_out[:,[2]])
imp_fare = Imputer(missing_values= 'NaN', strategy="mean",axis= 0)
X_test_out[:,[-1]] = imp.fit_transform(X_test_out[:,[-1]])


# Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_test_out = LabelEncoder()
X_test_out[:, 1] = labelencoder_X_test_out.fit_transform(X_test_out[:, 1])


#test_train split
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
X_test_out = sc.transform(X_test_out)




C:\Users\chall\Anaconda3\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype object was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


## model1 -  deep learning
### 2 hidden layers with 4 nodes each and activation function of relu

In [109]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier_dl  = Sequential()
classifier_dl.add(Dense(output_dim = 4,input_dim = 6, activation = 'relu',kernel_initializer = 'uniform'))
classifier_dl.add(Dense(output_dim = 3, activation = 'relu',kernel_initializer = 'uniform'))
classifier_dl.add(Dense(output_dim = 1, activation = 'sigmoid',kernel_initializer = 'uniform'))
# Compiling the ANN
classifier_dl.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier_dl.fit(X, y, batch_size = 10, epochs = 200)



C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=6, activation="relu", kernel_initializer="uniform", units=4)`
  """
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=3)`
  
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", kernel_initializer="uniform", units=1)`
  import sys


Epoch 1/200
891/891 [==============================] - 0s 437us/step - loss: 0.6894 - acc: 0.6083
Epoch 2/200
891/891 [==============================] - 0s 115us/step - loss: 0.6672 - acc: 0.6465
Epoch 3/200
891/891 [==============================] - 0s 118us/step - loss: 0.6260 - acc: 0.6734
Epoch 4/200
891/891 [==============================] - 0s 125us/step - loss: 0.6063 - acc: 0.6824
Epoch 5/200
891/891 [==============================] - 0s 123us/step - loss: 0.6001 - acc: 0.6902
Epoch 6/200
891/891 [==============================] - 0s 123us/step - loss: 0.5971 - acc: 0.6857
Epoch 7/200
891/891 [==============================] - 0s 113us/step - loss: 0.5919 - acc: 0.6902
Epoch 8/200
891/891 [==============================] - 0s 127us/step - loss: 0.5882 - acc: 0.6902
Epoch 9/200
891/891 [==============================] - 0s 119us/step - loss: 0.5850 - acc: 0.6914
Epoch 10/200
891/891 [==============================] - 0s 107us/step - loss: 0.5814 - acc: 0.6992
Epoch 11/200
891/89

891/891 [==============================] - 0s 135us/step - loss: 0.4416 - acc: 0.8114
Epoch 84/200
891/891 [==============================] - 0s 132us/step - loss: 0.4419 - acc: 0.8070
Epoch 85/200
891/891 [==============================] - 0s 113us/step - loss: 0.4420 - acc: 0.8058
Epoch 86/200
891/891 [==============================] - 0s 151us/step - loss: 0.4392 - acc: 0.8159
Epoch 87/200
891/891 [==============================] - 0s 133us/step - loss: 0.4427 - acc: 0.8159
Epoch 88/200
891/891 [==============================] - 0s 131us/step - loss: 0.4372 - acc: 0.8103
Epoch 89/200
891/891 [==============================] - 0s 137us/step - loss: 0.4382 - acc: 0.8114
Epoch 90/200
891/891 [==============================] - 0s 122us/step - loss: 0.4402 - acc: 0.8148
Epoch 91/200
891/891 [==============================] - 0s 132us/step - loss: 0.4400 - acc: 0.8126
Epoch 92/200
891/891 [==============================] - 0s 136us/step - loss: 0.4402 - acc: 0.8081
Epoch 93/200
891/891 [=

891/891 [==============================] - 0s 135us/step - loss: 0.4300 - acc: 0.8159
Epoch 166/200
891/891 [==============================] - 0s 128us/step - loss: 0.4371 - acc: 0.8159
Epoch 167/200
891/891 [==============================] - 0s 118us/step - loss: 0.4299 - acc: 0.8193
Epoch 168/200
891/891 [==============================] - 0s 134us/step - loss: 0.4288 - acc: 0.8238
Epoch 169/200
891/891 [==============================] - 0s 135us/step - loss: 0.4295 - acc: 0.8238
Epoch 170/200
891/891 [==============================] - 0s 115us/step - loss: 0.4279 - acc: 0.8227
Epoch 171/200
891/891 [==============================] - 0s 118us/step - loss: 0.4283 - acc: 0.8238
Epoch 172/200
891/891 [==============================] - 0s 128us/step - loss: 0.4343 - acc: 0.8171
Epoch 173/200
891/891 [==============================] - 0s 138us/step - loss: 0.4278 - acc: 0.8215
Epoch 174/200
891/891 [==============================] - 0s 136us/step - loss: 0.4223 - acc: 0.8249
Epoch 175/200


In [110]:
# Predicting the Test set results
y_pred = classifier_dl.predict(X_test_out)
y_pre_dl = (y_pred > 0.5)
y_pred_dl= y_pre_dl.astype(int)


In [111]:
y_pred_dl.shape

(418, 1)

In [112]:
y_pred_dl

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

## model2 - LogisticRegression

In [31]:

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(X, y)

# Predicting the Test set results
y_pred_lr = classifier_lr.predict((X_test_out))

In [97]:
import pickle
# save the model to disk
filename = 'classifier_lr.sav'
pickle.dump(classifier_lr, open(filename, 'wb'))

## model3 - KNN

In [32]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X, y)

# Predicting the Test set results
y_pred_knn = classifier_knn.predict(X_test_out)

In [98]:
import pickle
# save the model to disk
filename = 'classifier_knn.sav'
pickle.dump(classifier_knn, open(filename, 'wb'))

## model4 - SVC

In [33]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier_ksvm = SVC(kernel = 'rbf', random_state = 0)
classifier_ksvm.fit(X, y)

# Predicting the Test set results
y_pred_ksvm = classifier_ksvm.predict(X_test_out)

In [99]:
import pickle
# save the model to disk
filename = 'classifier_ksvm.sav'
pickle.dump(classifier_ksvm, open(filename, 'wb'))

## model5 - Random Forest

In [34]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 500, criterion = 'entropy', random_state = 0)
classifier_rf.fit(X, y)

# Predicting the Test set results
y_pred_rf = classifier_rf.predict(X_test_out)

In [100]:
import pickle
# save the model to disk
filename = 'classifier_rf.sav'
pickle.dump(classifier_rf, open(filename, 'wb'))

## model6 - naive bayes

In [35]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(X, y)

# Predicting the Test set results
y_pred_nb = classifier_nb.predict(X_test_out)

In [101]:
import pickle
# save the model to disk
filename = 'classifier_nb.sav'
pickle.dump(classifier_nb, open(filename, 'wb'))

## Ensembling
###  taking majority vote. most naive method But still good as first learning step .

In [156]:
y_pred_knn.shape

(418,)

In [157]:
y_pred_dl.shape

(418, 1)

In [163]:
out = y_pred_knn+y_pred_ksvm+y_pred_lr+y_pred_nb+y_pred_rf

In [164]:
out

array([4, 5, 4, 4, 5, 4, 5, 5, 5, 4, 4, 4, 5, 4, 5, 5, 4, 4, 5, 5, 4, 5,
       5, 5, 5, 4, 5, 4, 4, 4, 4, 4, 5, 5, 4, 4, 5, 5, 4, 4, 5, 4, 4, 5,
       5, 4, 4, 4, 5, 5, 4, 4, 5, 5, 4, 3, 4, 4, 4, 5, 4, 4, 4, 5, 5, 5,
       5, 4, 4, 5, 5, 4, 5, 4, 5, 4, 4, 5, 4, 5, 5, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5, 4, 5, 4, 4, 4, 5, 4, 5, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4,
       4, 5, 5, 5, 5, 4, 4, 5, 4, 5, 5, 4, 5, 4, 4, 5, 4, 5, 4, 4, 4, 4,
       5, 4, 4, 4, 4, 4, 5, 4, 5, 5, 5, 4, 4, 3, 4, 4, 4, 5, 5, 4, 4, 5,
       3, 4, 5, 5, 4, 5, 5, 5, 5, 4, 4, 5, 4, 5, 5, 5, 4, 4, 4, 4, 4, 5,
       5, 4, 5, 5, 4, 5, 5, 4, 5, 4, 5, 4, 4, 4, 4, 4, 5, 4, 5, 4, 5, 5,
       4, 5, 5, 5, 4, 5, 4, 4, 5, 4, 5, 4, 4, 4, 4, 5, 5, 4, 5, 5, 5, 4,
       5, 4, 5, 4, 5, 5, 4, 5, 4, 4, 4, 5, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5,
       5, 4, 5, 4, 5, 5, 5, 5, 5, 4, 4, 4, 4, 4, 4, 4, 5, 4, 4, 4, 5, 5,
       4, 4, 4, 4, 5, 4, 4, 4, 5, 5, 4, 5, 4, 4, 4, 4, 5, 5, 5, 5, 5, 4,
       4, 4, 4, 4, 4, 5, 4, 5, 4, 4, 5, 4, 4, 4, 4,

In [165]:
y_pred_dl

array([[1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
    

In [166]:
y_pred_knn

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [167]:
y_pred_ksvm

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [168]:
y_pred_lr

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [169]:
y_pred_nb

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [170]:
y_pred_rf

array([0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,

In [159]:
y_final = []
for i in range(0,418):
    a = out[i] + int(y_pred_dl[i])
    y_final.append(a)

In [160]:
len(y_final)

418

In [161]:
y_np_final/6
y_out = []
for i in y_final:
    if(i > 0.5):
        y_out.append(1)
    else:
        y_out.append(0)

In [162]:
len(y_out)

418

In [155]:
y_out

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,


### conclusion as of now:- most of the algorithms are found to be showing 1 as output while random forest showed many 0's. have to figure out why this behavoiur is exhibited.