In [41]:
# Data Preprocessing Template

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Importing the dataset
datatrain = pd.read_csv('train.csv')
datatest = pd.read_csv('test.csv')
y_train = datatrain.iloc[:,[1]].values
y = np.ravel(y_train)

In [42]:
datatrain.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [43]:
X = datatrain.iloc[:,[2,4,5,6,7,9]].values
X_test_scaled = datatest.iloc[:,[1,3,4,5,6,8]].values

In [44]:
len(X)

891

In [45]:
datatest.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [46]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values= 'NaN', strategy="mean",axis= 0)
X[:,[2]] = imp.fit_transform(X[:,[2]])

In [47]:
from sklearn.preprocessing import Imputer
imp = Imputer(missing_values= 'NaN', strategy="mean",axis= 0)
X_test_scaled[:,[2]] = imp.fit_transform(X_test_scaled[:,[2]])
X_test_scaled[:,[-1]] = imp.fit_transform(X_test_scaled[:,[-1]])

In [48]:

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 1] = labelencoder_X.fit_transform(X[:, 1])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()


In [49]:
len(datatrain.iloc[:,[2,4,5,6,7,9]].values)

891

In [50]:
X = X[:,1:]

In [51]:

# Encoding categorical data
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X_test_scaled[:, 1] = labelencoder_X.fit_transform(X_test_scaled[:, 1])
onehotencoder = OneHotEncoder(categorical_features = [1])
X_test_scaled = onehotencoder.fit_transform(X_test_scaled).toarray()


In [52]:
X = X[:,1:]
X_test_scaled = X_test_scaled[:,1:]


In [53]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X)
#X_test_scaled = sc.transform(X_test_scaled)


In [54]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
scr = StandardScaler()
X_test_scaled = sc.fit_transform(X_test_scaled)

In [55]:
X_train_scaled[0]

array([ 0.73769513,  0.82737724, -0.5924806 ,  0.43279337, -0.47367361,
       -0.50244517])

In [56]:
X_test_scaled[0]

array([ 0.75592895,  0.87348191,  0.3349926 , -0.49947002, -0.4002477 ,
       -0.49840706])

In [57]:

# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier_lr = LogisticRegression(random_state = 0)
classifier_lr.fit(X_train_scaled, y)

# Predicting the Test set results
y_pred_lr = classifier_lr.predict((X_test_scaled))
out = y_pred_lr


In [58]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier_knn.fit(X_train_scaled, y)

# Predicting the Test set results
y_pred_knn = classifier_knn.predict(X_test_scaled)

out = out+y_pred_knn

In [59]:
# Fitting Kernel SVM to the Training set
from sklearn.svm import SVC
classifier_ksvm = SVC(kernel = 'rbf', random_state = 0)
classifier_ksvm.fit(X_train_scaled, y)

# Predicting the Test set results
y_pred_ksvm = classifier_ksvm.predict(X_test_scaled)

out = out+y_pred_ksvm

In [60]:
# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 500, criterion = 'entropy', random_state = 0)
classifier_rf.fit(X_train_scaled, y)

# Predicting the Test set results
y_pred_rf = classifier_rf.predict(X_test_scaled)
out = out+y_pred_rf

In [61]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier_nb = GaussianNB()
classifier_nb.fit(X_train_scaled, y)

# Predicting the Test set results
y_pred_nb = classifier_nb.predict(X_test_scaled)

out = out+y_pred_nb

In [62]:
y_final = list()
out = out/5
for i in out:
    if(i>0.5):
        y_final.append(1)
    else:
        y_final.append(0)

In [63]:
pid = datatest['PassengerId'].values

In [64]:
submit_avg = np.column_stack((pid,y_final))

In [65]:
submit_avg

array([[ 892,    0],
       [ 893,    0],
       [ 894,    0],
       [ 895,    0],
       [ 896,    1],
       [ 897,    0],
       [ 898,    1],
       [ 899,    0],
       [ 900,    1],
       [ 901,    0],
       [ 902,    0],
       [ 903,    0],
       [ 904,    1],
       [ 905,    0],
       [ 906,    1],
       [ 907,    1],
       [ 908,    0],
       [ 909,    0],
       [ 910,    1],
       [ 911,    0],
       [ 912,    0],
       [ 913,    0],
       [ 914,    1],
       [ 915,    0],
       [ 916,    1],
       [ 917,    0],
       [ 918,    1],
       [ 919,    0],
       [ 920,    0],
       [ 921,    0],
       [ 922,    0],
       [ 923,    0],
       [ 924,    0],
       [ 925,    0],
       [ 926,    0],
       [ 927,    0],
       [ 928,    1],
       [ 929,    1],
       [ 930,    0],
       [ 931,    0],
       [ 932,    0],
       [ 933,    0],
       [ 934,    0],
       [ 935,    1],
       [ 936,    1],
       [ 937,    0],
       [ 938,    0],
       [ 939,

In [68]:
y_pred_knn

array([0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,

In [67]:
import keras
from keras.models import Sequential
from keras.layers import Dense
classifier_dl  = Sequential()
classifier_dl.add(Dense(output_dim = 4,input_dim = 6, activation = 'relu',kernel_initializer = 'uniform'))
classifier_dl.add(Dense(output_dim = 3, activation = 'relu',kernel_initializer = 'uniform'))
classifier_dl.add(Dense(output_dim = 1, activation = 'sigmoid',kernel_initializer = 'uniform'))
# Compiling the ANN
classifier_dl.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier_dl.fit(X_train_scaled, y, batch_size = 10, epochs = 200)



C:\Users\chall\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(input_dim=6, activation="relu", kernel_initializer="uniform", units=4)`
  """
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", kernel_initializer="uniform", units=3)`
  
C:\Users\chall\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", kernel_initializer="uniform", units=1)`
  import sys


Epoch 1/200
891/891 [==============================] - 0s 318us/step - loss: 0.6891 - acc: 0.6049
Epoch 2/200
891/891 [==============================] - 0s 123us/step - loss: 0.6724 - acc: 0.6162
Epoch 3/200
891/891 [==============================] - 0s 120us/step - loss: 0.6323 - acc: 0.6162
Epoch 4/200
891/891 [==============================] - 0s 114us/step - loss: 0.5875 - acc: 0.6162
Epoch 5/200
891/891 [==============================] - 0s 109us/step - loss: 0.5614 - acc: 0.6162
Epoch 6/200
891/891 [==============================] - 0s 115us/step - loss: 0.5482 - acc: 0.6162
Epoch 7/200
891/891 [==============================] - 0s 113us/step - loss: 0.5391 - acc: 0.6162
Epoch 8/200
891/891 [==============================] - 0s 122us/step - loss: 0.5322 - acc: 0.7710
Epoch 9/200
891/891 [==============================] - 0s 107us/step - loss: 0.5265 - acc: 0.7946
Epoch 10/200
891/891 [==============================] - 0s 109us/step - loss: 0.5210 - acc: 0.7957
Epoch 11/200
891/89

891/891 [==============================] - 0s 100us/step - loss: 0.4262 - acc: 0.8272
Epoch 84/200
891/891 [==============================] - 0s 100us/step - loss: 0.4262 - acc: 0.8260
Epoch 85/200
891/891 [==============================] - 0s 100us/step - loss: 0.4256 - acc: 0.8193
Epoch 86/200
891/891 [==============================] - 0s 95us/step - loss: 0.4252 - acc: 0.8260
Epoch 87/200
891/891 [==============================] - 0s 106us/step - loss: 0.4248 - acc: 0.8238
Epoch 88/200
891/891 [==============================] - 0s 100us/step - loss: 0.4241 - acc: 0.8272
Epoch 89/200
891/891 [==============================] - 0s 98us/step - loss: 0.4243 - acc: 0.8249
Epoch 90/200
891/891 [==============================] - 0s 100us/step - loss: 0.4242 - acc: 0.8272
Epoch 91/200
891/891 [==============================] - 0s 100us/step - loss: 0.4233 - acc: 0.8249
Epoch 92/200
891/891 [==============================] - 0s 99us/step - loss: 0.4235 - acc: 0.8238
Epoch 93/200
891/891 [====

891/891 [==============================] - 0s 120us/step - loss: 0.4092 - acc: 0.8227
Epoch 166/200
891/891 [==============================] - 0s 109us/step - loss: 0.4092 - acc: 0.8227
Epoch 167/200
891/891 [==============================] - 0s 105us/step - loss: 0.4092 - acc: 0.8227
Epoch 168/200
891/891 [==============================] - 0s 114us/step - loss: 0.4095 - acc: 0.8238
Epoch 169/200
891/891 [==============================] - 0s 122us/step - loss: 0.4096 - acc: 0.8227
Epoch 170/200
891/891 [==============================] - 0s 123us/step - loss: 0.4090 - acc: 0.8204
Epoch 171/200
891/891 [==============================] - 0s 122us/step - loss: 0.4087 - acc: 0.8215
Epoch 172/200
891/891 [==============================] - 0s 128us/step - loss: 0.4089 - acc: 0.8215
Epoch 173/200
891/891 [==============================] - 0s 131us/step - loss: 0.4089 - acc: 0.8238
Epoch 174/200
891/891 [==============================] - 0s 115us/step - loss: 0.4084 - acc: 0.8238
Epoch 175/200


In [71]:
# Predicting the Test set results
y_pred = classifier_dl.predict(X_test_scaled)
y_pre_dl = (y_pred > 0.5)
y_pred_dl= y_pre_dl.astype(int)


In [ ]:
np.savetxt("submit_avg.csv", submit, dddelimiter=",")

In [ ]:
submit_rf = np.column_stack((pid,y_pred_rf))
np.savetxt("submit_rf.csv", submit, delimiter=",")

In [ ]:
submit_ksvm = np.column_stack((pid,y_pred_ksvm))
np.savetxt("submit_ksvm.csv", submit, delimiter=",")

In [ ]:
submit_ksvm = np.column_stack((pid,y_pred_knn))
np.savetxt("submit_knn.csv", submit, delimiter=",")

In [ ]:
submit_ksvm = np.column_stack((pid,y_pred_nb))
np.savetxt("submit_nb.csv", submit, delimiter=",")

In [ ]:
submit_ksvm = np.column_stack((pid,y_pred_lr))
np.savetxt("submit_lr.csv", submit, delimiter=",")